sudo: required
dist: trusty
language: ruby
before_install:
- google-chrome --version
- curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome.deb
- rm google-chrome.deb
- google-chrome --version
addons:
  firefox: latest
rvm:
- ruby-head
- 2.3.0
- 2.2
- 2.1
matrix:
  allow_failures:
  - rvm: ruby-head
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
  - secure: FjSRWJJYC6h62wLwiT9p8ud3Tgq5rPMnA5LLJ6Nk65aA5zssfnxrVJxQiw5YU8iox+rs+LlC1mMD7TVl3ZjyQKe/vJZJP3WngN18hngGb2kNH12PX3W3rc8GT89wtNzSsjXChjyNqTZvPuA90N29gJg0foWZNpLTSkenXjQ1nb8Pb0XTrEngQ2/lT2UGGSDowko91aEJqKYcthYryn2eeDl2+i6NKcRqCk//pQakfwLCQfFDaNKHebKnKPfZRb5qamgcY8I9OoGNO4IVx/wVCoGhU/VSHcXQAqMtSXI7BY9mYQWSORDzqZLGVrWmalokJ1u1hZcfJjEbMpPSIW3YDYtYPTflQwOWNMOBEduL5hmCcLpMhB0Xhi7q92GpYnrWp4hXSMCp0Gu8rFIVKEkiAdDOBU1gVtNxfcIiDV+cYQEuW55nbUGvLEx/vMPeEnvcjA1Xf2Tm/sGtmYvbAU2d0fHFHKzSfspejicA3nS/1MYAPc4zyml4T1NzCxu6JEmR0DzTujELt+YPbHtDLVXa7n2hY7Dz+LBE+DdZC8Ln1/TTq3cv0WNe+T0uxHPKuZUE3J6eawWJiBs++qVFAMc508rovuYqqaIfzxu0Jn/SAixQSA0fN9/gkakxxWWT02nmJ5nUIPgiAKMjOestu7H8GwZ0lnKlaC7GCpp7VZTsnuA=
  - secure: lVnMXaqFGveosi2KRyYoWNjhp7WKKc+uqrs0d5mVQ1v6cVZFgAJshQV52CBbjREL0DrZnQiQE/7ZyFhu+uxxWqbKzE2Cki3CEo4cgUIZmZqU595Fmh+agXAnqblWU/ZJlu5q8i6pTu9BD9ZqJrofrt24BrG+1EqNkFyj6t2ZvxtLWxky4H6U+ueMLxAL4asktkkOUSQ7EPRwp7Let2Tep3smDvs1HBIa4M3MIXL5ETXoI9TU2uK2aO4jQA1EjS2ltDuGgXYfSBB0Vb0Zcpnjjl8czZglELzMTaP2dOM2Nahko3Z2rjtpbfa7TGC5gtuw3Ski6V+gXZWkhZTlCIi2KrIhY20vc//kYZfkNF2M1NvpQ5V1nwoPci2b3TbEEKM7a29KQhtAxWJq3B1ZAA4MYM0ABnm8+VEcW85LqZq78SGV7oPxW5642vVYCCWG6xxliNVDQzszkp642kxUggpkM3YTxkMe+3du1Qmh2gqny4H3gA6SC6V3VUurdMfZgGuoHqypl5Dxktq+CSGCi4jqYXLWx3VwbyGMjpWvRIHYnQ51L7+oFOc/SdjGErQpStnMTmweiSM1S1sAJwaTexTZ74or38FfU8kE1bdin+W39sKqvUHTuTym9QSKUay41sGbFnfu4H6Hu7FxPreg7Tc0CnXNCUHtJZ0py04d7i9Y6EA=
